default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ^.vscode/
      - id: mixed-line-ending

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
    # cleans the .ipynbs (removes outputs, resets all cell-ids to 0..N, cleans steps)
    # also clean any kernel information left after execution
    - id: nbstripout
      name: clean .ipynb output
      args: [--extra-keys, "metadata.language_info"]
      files: examples/.*\.ipynb$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff # linter
        args: [--fix]
      - id: ruff-format # formatter

  - repo: https://github.com/crate-ci/typos
    rev: v1.38.1
    hooks:
      - id: typos

ci:
  autofix_commit_msg: |
    [pre-commit] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit] pre-commit autoupdate"
  autoupdate_schedule: monthly
  skip: []
  submodules: false
