name: examples

on:
  push:
    branches:
      - main
  pull_request:

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  examples-to-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip 

    - name: Install mrpro and dependencies
      run: pip install --index-url=https://download.pytorch.org/whl/cpu --extra-index-url https://pypi.org/simple/ --upgrade --upgrade-strategy "eager" -e .[dev]

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build examples

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "examples/_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      if: >-
        ${{ github.event.workflow_run.event == 'push' &&
          github.event.workflow_run.head_branch == 'main' &&
          github.event.workflow_run.conclusion != 'cancelled' &&
          github.event.workflow_run.conclusion != 'skipped' }} 
      id: deployment
      uses: actions/deploy-pages@v4
